### ISSUE TITLE
Messages are not updated

### ISSUE THREAD

**Issue by davityavryan** [marceloadsj/react-indicative-hooks#7]
Hey @marceloadsj,

[This line](https://github.com/marceloadsj/react-indicative-hooks/blob/ab551159a07a408bd3fc753091c1249b3d7c86d0/src/index.js#L42) has a problem. Basically if you pass messages to `useValidateAll` then they are static and are not changing. This is a big problem if you use translations and messages have changed on the fly (without refresh of a page).

Would be nice to have them as a dependency (maybe even rules should be a dependency, I don't know.).

If you are ok the I will open a PR with changes.

p.s. same for `useValidate`.

**Comment by marceloadsj** [comment]
Hello my friend. Yeah, you're right!
Of course, feel free to send PR and I can merge and release a new version.

Checking the code, it's not even a good practice, I wrote that lib when I was starting to learn react hooks. haha. I will try to revisit the library and double check everything, creating tests and so on.

Thank you for your feedback man! :)

**Comment by davityavryan** [comment]
Cool, will prepare PR soon. :)

Thanks to you I have simple solution for validating fields.

**Comment by davityavryan** [comment]
It appears that you need help. I saw 10 unique vulnerabilities and code can be reorganized a bit. Would you mind other PR-s with bigger changes?

**Comment by marceloadsj** [comment]
Great, feel free man! And I really appreciate your help. :D

**Comment by marceloadsj** [comment]
It's okay if I check and merge by the end of the day (20/jan UTC+1)? Haha, I'm currently at work now, and I will not be able to check and release right now.

**Comment by davityavryan** [comment]
Cool.
Will do changes later from home. (same thing here)
Sure, no worries. I should release bug fix on tomorrow. :)

**Comment by davityavryan** [comment]
Hey @marceloadsj ,
Thanks a lot.
And I am sorry to tell you that I did pure job on testing ;( and test didn't catch the bug but basically I created loop. ;(
I should have used `[Object.values(data), Object.values(rules), Object.values(messages)]` as a dependency instead of `[...Object.values(data), rules, messages]` because it produces different references and `useEffect` runs again and then developer's component runs again and then again and again... ;(
I will open a PR fix now but you should deprecate `1.2.3` version (https://docs.npmjs.com/cli/deprecate) as of it can cause problems for users.

**Comment by davityavryan** [comment]
Can I ask you to have a look and release if you have several minutes? ;(

**Comment by davityavryan** [comment]
Again, Sorry and let's add more tests so that this kind of thing would not happen again.

**Comment by marceloadsj** [comment]
Hey man. Sorry, I couldn't tested properly from my side. My fault!
I will try to release right now an update. Tks for testing! :)

**Comment by marceloadsj** [comment]
Released: 1.2.4. Tks man! :D

**Comment by marceloadsj** [comment]
To let you know, I've deprecated the version 1.2.3! haha

**Comment by davityavryan** [comment]
Very good. Thanks a lot. Just tested, everything works as expected. :)
Again, sorry. I will try to help you with adding more tests.

**Comment by marceloadsj** [comment]
Great, don't worry! And thanks for all your help. :)

**Comment by davityavryan** [comment]
Never-mind. :) UMD transpiled version is doing wrong things. ;( I will post my findings ;(

"Help", :( I pushed 2 changes to your package and both are not working well. :|
Usually this is not, I am working. probably I am doing mistakes because I am in a rush. I will postpone our fix and do proper testing locally.

![image](https://user-images.githubusercontent.com/8176311/72829088-54888380-3c7e-11ea-8fe1-5947a3ea9a42.png)

As you can see message remains same but other strings are updated.

**Comment by davityavryan** [comment]
Can you please re-open this issue on me? I can't update it.

**Comment by davityavryan** [comment]
It works!!! I was checking production by mistake. :D
I am definitely in hurry.

Thanks again and sorry for spamming
